### ISSUE TITLE
❗Create Page From Database in Notion ... DUPLICATE + TRIPLICATE Formatted Sections in Columns ❗ 

### ISSUE THREAD

**Issue by EDGAR-WGSX** [TomFrankly/pipedream-notion-voice-notes#3]
@TomFrankly 

⭐Hi Tom ... thank you for the opportunity to share my issue here ...

1.) Once the "FORMATTER" creates an elegant version of the transcript with the headers I use i.e. ... "Main Points" ... "Action Items" ... "Follow-Up Questions" ... I send it to Create Page from Database

2.) I have properties set-up in my database and named them "Main Points" ... "Action Items" ..."Follow-Up Questions" ... and the properties show up in the configuration part of this step.

3.) in the Configuration I assign the appropriate path to each of the properties ... i.e.
a) Main Points: {{steps.formatter.$return_value.main_points}}
b) Follow Up Questions: {{steps.formatter.$return_value.follow_up_questions}}
c) Potential Arguments: {{steps.formatter.$return_value.potential_arguments_against}}

❗ ISSUE ❗ ... repeated sections in each column
the resulting page displays the following data under each of the section headings ...
A) ... Main Points:   displays 3 items (a + b + c):  MAIN POINTS + FOLLOW-UP QUESTIONS + POTENTIAL ARGUMENTS
B) ... Follow-Up Questions:   displays 2 items (b + c):  FOLLOW-UP QUESTIONS + POTENTIAL ARGUMENTS
A) ... Potential Arguments:   displays 1 items (c): POTENTIAL ARGUMENTS

I fully understand you are "involved with really pressing activities" ... and so ... if anyone else you might suggest can help me ... I will greatly appreciate your guidance ...

🙏 THANK YOU !!! 🙏
EDGAR !!!
111stellaturner@gmail.com

**Comment by TomFrankly** [comment]
I see, so you're trying to send those values to database properties rather than putting them in the page body.

Unfortunately, that's not something I can support right now. But I have shipped a new version of the workflow that has a lot of improvements, and also surfaces a lot more data in the logs: https://thomasjfrank.com/pipedream-notion-voice-notes-dropbox/

What you could do is add an additional method that takes the lists from the formatted_chat object and sends them to database properties.

You'd need to follow the Notion API docs, and also fork this repo's code and deploy it as a CLI component in your own Pipedream account. Pipedream does have good documentation for this: https://pipedream.com/docs/cli/install/

Unfortunately this is a use case I can't support, so all I can do is share these resources for now!

**Comment by EDGAR-WGSX** [comment]
(NEW ❗) ... 🙏 THANK YOU !!! 🙏 … 

Tom … I am very grateful for ALL of your time and ALL of your suggestions !!!

 

I have zero background in coding and programming … 

all my learning has occurred in the past 80 hours  … 

and ALL of it based on YOUR tutorials … 
as well as additional reading on Pipedream docs … it is all way out of my league … 

 

I wish you ALL OF THE SUCCESS and JOY that YOU DESERVE … 

 

 

 

If you have any questions, email me, call me, or text me (203) 520-8432 cell / text

 

 

🙏 THANK YOU !!! 🙏

 

 




 

⭐ EDGAR !!! ⭐

Edgar Stella-Turner

(203) 520-8432 cell / text

  

__________________________________________________

 

SPIRIT * EXCHANGE

 <http://www.spirit-exchange.com/> www.spirit-exchange.com

 

Contact me:

 ***@***.***> ***@***.***   ...
