### ISSUE TITLE
Problem with Summary Language in another language exceeding tokens

### ISSUE THREAD

**Issue by kykpeng** [TomFrankly/pipedream-notion-voice-notes#31]
Hi Tom, I had a 2-hour test audito piece in Chinese.  My setup:

```
ChatGPT Model: gpt-3.5-turbo
Transcript Language (Optional): zh
Enable Advanced Options: true
Summary Density (Advanced): 2750
Summary Verbosity (Advanced): Medium
Summary Language (Advanced): zh
Add Translation (Transcript): Don't Translate
Model Temperature: -
Audio File Chunk Size: 24
Disable Moderation Check: true
``` 

The error:
```
10/16/2023, 3:30:05 PM
User specified zh for the summary. Checking if the transcript language matches...

10/16/2023, 3:30:05 PM
Attempt 1: Detecting transcript language using ChatGPT

10/16/2023, 3:30:05 PM
Attempt 1 for language detection failed with error: 400 This model's maximum context length is 4097 tokens. However, your messages resulted in 8943 tokens. Please reduce the length of the messages.. Retrying...

10/16/2023, 3:30:06 PM
Attempt 2: Detecting transcript language using ChatGPT

10/16/2023, 3:30:07 PM
Attempt 2 for language detection failed with error: 400 This model's maximum context length is 4097 tokens. However, your messages resulted in 8943 tokens. Please reduce the length of the messages.. Retrying...

10/16/2023, 3:30:10 PM
Attempt 3: Detecting transcript language using ChatGPT

10/16/2023, 3:30:10 PM
Attempt 3 for language detection failed with error: 400 This model's maximum context length is 4097 tokens. However, your messages resulted in 8943 tokens. Please reduce the length of the messages.. Retrying...

10/16/2023, 3:30:17 PM
Attempt 4: Detecting transcript language using ChatGPT
``` 

Looks like this is a matter of ... need to split fileInfo.paragraphs.transcript into chunks?

**Comment by TomFrankly** [comment]
@kykpeng yep, this has happened with other users who are transcribing into non-English languages as well.

I believe this is due to the fact that characters in certain languages consume more tokens than others – apparently Chinese characters take up 2-3x more tokens than English characters.

This may require a significant refactor of some of my code, as the `makeParagraphs` method creates 1,200-character paragraphs.

In English, these are always short enough to not hit the token limit. But in Chinese, they must be going over that limit.

I'm very short on time for development right now, so I probably won't be able to fix this for a while. However, we'll be building a much better version of this workflow into Flylighter's mobile app, which is launching soon. You can join our waitlist here: https://flylighter.com/

**Comment by TomFrankly** [comment]
@kykpeng got around to fixing this, actually!

I've just shipped a new version of the workflow that works better for non-English characters. It also guarantees each paragraph can be no more than 1,800 characters, so it should prevent this error.

You can update your workflow by following these instructions: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update
