### ISSUE TITLE
Invalid Duration Number

### ISSUE THREAD

**Issue by rubinsandwich** [TomFrankly/pipedream-notion-voice-notes#50]
I'm getting "invalid duration number (thrown from calculateTranscriptCost)" on about half of my audio file uploads. Not sure why it works sometimes and not others.

```
Error
Invalid duration number (thrown from calculateTranscriptCost). 
    at Object.calculateTranscriptCost (file:///pipedream/dist/code/.../code/Notion-Voice-Notes.mjs:1211:11)
    at Object.run (file:///pipedream/dist/code/.../code/Notion-Voice-Notes.mjs:2048:41)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)
(notion_voice_notes)
```

**Comment by TomFrankly** [comment]
@rubinsandwich what app are you using to record your files, and what format are they in? I've heard from a couple other folks that certain apps create weird .m4a files that can't be read for duration.

**Comment by TomFrankly** [comment]
@rubinsandwich duration is separate from ChatGPT issues, as I'm using the [music-metadata](https://www.npmjs.com/package/music-metadata) npm package to get durations.

Aside from duration (which is 100% a conflict between your mp3 files and that npm package), I have noticed OpenAI having more platform instability lately. The other day, I processed a file that needed 3 chunks at the ChatGPT (not transcription) stage.

Chunks 1 and 3 were processed very quickly, but Chunk 2 took nearly 10 minutes. I'm on a paid Pipedream account, so I have my personal workflow set to timeout after 12 minutes instead of 5 – otherwise, it would have failed.

There might be some further optimizations I can make in that regard. In the mean time, I did ship a couple updates recently that may help with consistency - you can update like so: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Comment by rubinsandwich** [comment]
OK. It does seem to be an issue with the app or file format (mp3) for the audio. I tried a sample with iOS voice memos for a 45min recording and it worked fine. Thanks again for making such an amazing tool!
