### ISSUE TITLE
Support for additional sections in the notion page

### ISSUE THREAD

**Issue by thestumonkey** [TomFrankly/pipedream-notion-voice-notes#61]
This notion page is tailored to a very specific type of content that is ideally suited for Tom.  The rest of us would like to customise what sections appear in the notion page.
I don't seem to be able to create a PR, but I made a fork here:  https://github.com/thestumonkey/pipedream-notion-voice-notes

Ideally you would be able to customise these within the pipedream workflow.

**Comment by TomFrankly** [comment]
@thestumonkey we'll also be adding a more customizable version of this to Flylighter mobile in the (hopefully near) future: https://flylighter.com/

Part of the reason I haven't added more choices is that I've actually run up against the file-size limit for single files within Pipedream actions. I can move things into other files and modularize, but right now I have very little time for programming, so I'm not prioritizing that since we'll be building a much better version of this into Flylighter anyway.

**Comment by thestumonkey** [comment]
Interesting!  Let me know if you need QA services on flylighter.
