### ISSUE TITLE
Sending File to OpenAI

### ISSUE THREAD

**Issue by dbudziak** [TomFrankly/pipedream-notion-voice-notes#78]
**Describe the bug**
On the final step of the workflow I continue to get this error:
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error. 

I have created a new openAI account, generated new keys, and have $10 worth of credits and updated billing informatin.

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google Drive

**Have you tried updating your workflow?**
Yes, this is using the new workflow

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
During normal, automated runs. During testing it works as expected

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
Checking that file is under 300mb...
File size is approximately 0.8mb.
File is under the size limit. Continuing...
No language set. Whisper will attempt to detect the language.
Successfully got duration: 190 seconds
Chunking file: /tmp/TEST.m4a
Transcribing file: chunk-000.m4a
Attempting to clean up the /tmp/ directory...
Cleaning up /tmp/chunks-2eEl2zmyKwQxkdLMArkD4PXYZV0...
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by TomFrankly** [comment]
@dbudziak if your account has real-money credits (non-promo credits), and you're using an API key you generated after adding those credits, then this is just due to OpenAI's service being overloaded with requests.

"Connection Error" means OpenAI rejected the connection request. I don't think there's anything we can do other than try again later when it happens, and within the limitations of Pipedream's free account, that means you'll need to go into the Pipedream dashboard and Replay the failed run.
